#!/bin/bash
export DRONE_ID=1
export DRONE_MARKER_ID=1
export DRONE_IP=192.168.1.254

export DRONE_SAFE_MAX_ANGLE=85
export DRONE_SAFE_DISARM_DELAY=0.2

export MAVROS_GCS_IP=
export MAVROS_FCU_URL='/dev/ttyACM0:921600'
export MAVROS_FCU_PORT=14101

export DRONE_REG_USE_PLANNER=False
export DRONE_REG_USE_GEO_MODE=False

export USE_POSE_REG=False

