// Generated by gencpp from file drone_msgs/DronePose.msg
// DO NOT EDIT!


#ifndef DRONE_MSGS_MESSAGE_DRONEPOSE_H
#define DRONE_MSGS_MESSAGE_DRONEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace drone_msgs
{
template <class ContainerAllocator>
struct DronePose_
{
  typedef DronePose_<ContainerAllocator> Type;

  DronePose_()
    : point()
    , course(0.0)  {
    }
  DronePose_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , course(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef float _course_type;
  _course_type course;





  typedef boost::shared_ptr< ::drone_msgs::DronePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_msgs::DronePose_<ContainerAllocator> const> ConstPtr;

}; // struct DronePose_

typedef ::drone_msgs::DronePose_<std::allocator<void> > DronePose;

typedef boost::shared_ptr< ::drone_msgs::DronePose > DronePosePtr;
typedef boost::shared_ptr< ::drone_msgs::DronePose const> DronePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_msgs::DronePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_msgs::DronePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_msgs::DronePose_<ContainerAllocator1> & lhs, const ::drone_msgs::DronePose_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point &&
    lhs.course == rhs.course;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_msgs::DronePose_<ContainerAllocator1> & lhs, const ::drone_msgs::DronePose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::DronePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::DronePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::DronePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::DronePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::DronePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::DronePose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_msgs::DronePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3922f772bbf0305ac9710fa392aba5a";
  }

  static const char* value(const ::drone_msgs::DronePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3922f772bbf0305ULL;
  static const uint64_t static_value2 = 0xac9710fa392aba5aULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_msgs::DronePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_msgs/DronePose";
  }

  static const char* value(const ::drone_msgs::DronePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_msgs::DronePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point point\n"
"float32 course\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::drone_msgs::DronePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_msgs::DronePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.course);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DronePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_msgs::DronePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_msgs::DronePose_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "course: ";
    Printer<float>::stream(s, indent + "  ", v.course);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MSGS_MESSAGE_DRONEPOSE_H
