// Generated by gencpp from file drone_msgs/RoomParams.msg
// DO NOT EDIT!


#ifndef DRONE_MSGS_MESSAGE_ROOMPARAMS_H
#define DRONE_MSGS_MESSAGE_ROOMPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace drone_msgs
{
template <class ContainerAllocator>
struct RoomParams_
{
  typedef RoomParams_<ContainerAllocator> Type;

  RoomParams_()
    : lines()
    , points()  {
    }
  RoomParams_(const ContainerAllocator& _alloc)
    : lines(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::drone_msgs::RoomParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_msgs::RoomParams_<ContainerAllocator> const> ConstPtr;

}; // struct RoomParams_

typedef ::drone_msgs::RoomParams_<std::allocator<void> > RoomParams;

typedef boost::shared_ptr< ::drone_msgs::RoomParams > RoomParamsPtr;
typedef boost::shared_ptr< ::drone_msgs::RoomParams const> RoomParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_msgs::RoomParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_msgs::RoomParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_msgs::RoomParams_<ContainerAllocator1> & lhs, const ::drone_msgs::RoomParams_<ContainerAllocator2> & rhs)
{
  return lhs.lines == rhs.lines &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_msgs::RoomParams_<ContainerAllocator1> & lhs, const ::drone_msgs::RoomParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::RoomParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_msgs::RoomParams_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::RoomParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_msgs::RoomParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::RoomParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_msgs::RoomParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_msgs::RoomParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "722c360e0d28cee48e7fbb2df2294d61";
  }

  static const char* value(const ::drone_msgs::RoomParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x722c360e0d28cee4ULL;
  static const uint64_t static_value2 = 0x8e7fbb2df2294d61ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_msgs::RoomParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_msgs/RoomParams";
  }

  static const char* value(const ::drone_msgs::RoomParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_msgs::RoomParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] lines\n"
"geometry_msgs/Point[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::drone_msgs::RoomParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_msgs::RoomParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lines);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoomParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_msgs::RoomParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_msgs::RoomParams_<ContainerAllocator>& v)
  {
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_MSGS_MESSAGE_ROOMPARAMS_H
