/**:    
  ros__parameters:  
    plugin_allowlist: 
      - local_position
      # - imu
      # - global_position 
      # - gps_rtk
      # - gps_status 
      - setpoint_position 
      - setpoint_velocity 
    

# List of available plugins

    #   gps_rtk,
    #   gps_status,
    #   odometry,
    #   companion_process_status,
    #   debug_value,
    #   esc_status,
    #   esc_telemetry,
    #   fake_gps,
    #   ftp,
    #   gps_input, 
    #   hil,
    #   landing_target,
    #   log_transfer,
    #   mag_calibration_status,
    #   manual_control,
    #   mocap_pose_estimate,
    #   mount_control,
    #   nav_controller_output,
    #   obstacle_distance,
    #   onboard_computer_status,
    #   play_tune,
    #   px,
    #   rangefinder,
    #   setpoint_accel,
    #   setpoint_attitude,
    #   # setpoint_position,
    #   setpoint_trajectory,
    #   # setpoint_velocity,
    #   tdr_radio,
    #   trajectory,
    #   tunnel,
    #   vibration,
    #   vision_pose,
    #   vision_speed,
    #   wheel_odomotry,
    #   image_pub,
    #   cam_imu_sync,
    #   camera