# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drone_msgs/DroneInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import drone_msgs.msg
import geometry_msgs.msg

class DroneInfo(genpy.Message):
  _md5sum = "142d303be68c1b2c6c6b79486ae3db7b"
  _type = "drone_msgs/DroneInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 team_num   # number of team (0,1..n)
int8 id_drone   # id of drone (0,1..n)
int8 id_marker  # number of marker id
float32 health  # health of drone (100%..0%)
string ip
drone_msgs/DronePose pose   # ENU position of drone

================================================================================
MSG: drone_msgs/DronePose
geometry_msgs/Point point
float32 course

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['team_num','id_drone','id_marker','health','ip','pose']
  _slot_types = ['int8','int8','int8','float32','string','drone_msgs/DronePose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       team_num,id_drone,id_marker,health,ip,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DroneInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.team_num is None:
        self.team_num = 0
      if self.id_drone is None:
        self.id_drone = 0
      if self.id_marker is None:
        self.id_marker = 0
      if self.health is None:
        self.health = 0.
      if self.ip is None:
        self.ip = ''
      if self.pose is None:
        self.pose = drone_msgs.msg.DronePose()
    else:
      self.team_num = 0
      self.id_drone = 0
      self.id_marker = 0
      self.health = 0.
      self.ip = ''
      self.pose = drone_msgs.msg.DronePose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3bf().pack(_x.team_num, _x.id_drone, _x.id_marker, _x.health))
      _x = self.ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3df().pack(_x.pose.point.x, _x.pose.point.y, _x.pose.point.z, _x.pose.course))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = drone_msgs.msg.DronePose()
      end = 0
      _x = self
      start = end
      end += 7
      (_x.team_num, _x.id_drone, _x.id_marker, _x.health,) = _get_struct_3bf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ip = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.pose.point.x, _x.pose.point.y, _x.pose.point.z, _x.pose.course,) = _get_struct_3df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3bf().pack(_x.team_num, _x.id_drone, _x.id_marker, _x.health))
      _x = self.ip
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3df().pack(_x.pose.point.x, _x.pose.point.y, _x.pose.point.z, _x.pose.course))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = drone_msgs.msg.DronePose()
      end = 0
      _x = self
      start = end
      end += 7
      (_x.team_num, _x.id_drone, _x.id_marker, _x.health,) = _get_struct_3bf().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ip = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.ip = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.pose.point.x, _x.pose.point.y, _x.pose.point.z, _x.pose.course,) = _get_struct_3df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3bf = None
def _get_struct_3bf():
    global _struct_3bf
    if _struct_3bf is None:
        _struct_3bf = struct.Struct("<3bf")
    return _struct_3bf
_struct_3df = None
def _get_struct_3df():
    global _struct_3df
    if _struct_3df is None:
        _struct_3df = struct.Struct("<3df")
    return _struct_3df
